language: node_js
node_js:
  - "lts/*"
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install --global gulp-cli
  - npm install --global gulp@4.0.0
  - npm install
script:
  - echo "build index.html"
  - gulp package

notifications:
  email:
    on_success: change
    on_failure: change
